export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const SET_SELECTED = 'SET_SELECTED'

export const CLEAR_PROJECT = 'CLEAR_PROJECT'
export const ADD_PROJECT_DIR = 'ADD_PROJECT_DIR'
export const ADD_PROJECT_FILE = 'ADD_PROJECT_FILE'
export const SET_FILE_CONTENTS = 'SET_FILE_CONTENTS'

export const SET_EDITOR_MENU = 'SET_EDITOR_MENU'